name: Build Android release for ChatAI
on:
  create:
    tags:
      - 'v*.*.*'
    branches:
      - master
jobs:
  build-android:
    name: Build and Publish Android APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Cordova and dependencies
        run: |
          npm install -g cordova
          cordova platform add android@11.0.0
      - name: Change res
        run: | 
          cp -rf res/* platforms/android/app/src/main/res
          cp -r index.html www/
      - name: cordova prepare
        run: cordova prepare
      - name: Change Version
        run: |
          tag_name=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          tag_name=`echo $tag_name| sed 's/v//'`
          sed -i "s/\"version\"=\".*\"/\"version\"=\"$tag_name\"/" config.xml
          sed -i "s/\"version\"=\".*\"/\"version\"=\"$tag_name\"/" platforms/android/app/src/main/res/xml/config.xml
          sed -i "s/\"version\": \".*\"/\"version\": \"$tag_name\"/" package.json
          sed -i "s/\"versionName\"=\".*\"/\"versionName\"=\"$tag_name\"/" platforms/android/app/src/main/AndroidManifest.xml
          sed -i "s/versionName=\".*\"/versionName=\"$tag_name\"/" platforms/android/CordovaLib/AndroidManifest.xml
          sed -i "s/versionCode=\".*\"/versionCode=\"$tag_name\"/" platforms/android/CordovaLib/AndroidManifest.xml
      - name: Upload Version artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ChatAI Version
          path: package.json

      - name: Build APK
        run: cordova build android --release -- --packageType apk --keystore=chatai-release-key.keystore  --alias=$KEY_ALIAS --storePassword=$STORE_PASSWORD --password=$KEY_PASSWORD
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ChatAI
          path: platforms/android/app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ChatAI
          path: platforms/android/app/build/outputs/apk/release/app-release.apk

      - name: Upload APK
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: platforms/android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive